name: ScalaTest
main: com.edawg878.bukkit.BukkitMain
version: 1
load: startup
commands:
  tier: {}
  perk: {}
  credit: {}
  group: {}
  playTime: {}
  seen: {}
  whoIs: {}
  plot:
    aliases: [p, plotme]